# Project
version=1.0.2.1
group=com.devnemo.nemos.backpacks
java_version=21

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# Mod
mod_name=Nemo's Backpacks
mod_author=DevNemo
mod_id=nemos_backpacks
license=MIT
credits=DevNemo
description=Add colorful backpacks to Minecraft!

# NeoForge
neoforge_version=21.1.77
neoforge_loader_version_range=[4,)

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
